<a href="https://colab.research.google.com/github/Josembp18/DataScience/blob/main/C_4_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

print("=== ARRAYS 1D Y 2D CON NUMPY - ATRIBUTOS Y SLICING ===\n")

# 1. CREACIÓN DE ARRAYS 1D
print("1. ARRAYS UNIDIMENSIONALES (1D):")
# Crear array 1D a partir de una lista
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Array 1D:", array_1d)

# Mostrar atributos del array 1D
print("   .shape  :", array_1d.shape)    # Forma/dimensiones
print("   .ndim   :", array_1d.ndim)     # Número de dimensiones
print("   .dtype  :", array_1d.dtype)    # Tipo de datos
print("   .size   :", array_1d.size)     # Total de elementos
print("   .itemsize:", array_1d.itemsize, "bytes") # Tamaño de cada elemento

print("\n" + "="*60)


=== ARRAYS 1D Y 2D CON NUMPY - ATRIBUTOS Y SLICING ===

1. ARRAYS UNIDIMENSIONALES (1D):
Array 1D: [ 1  2  3  4  5  6  7  8  9 10]
   .shape  : (10,)
   .ndim   : 1
   .dtype  : int64
   .size   : 10
   .itemsize: 8 bytes



In [ ]:
# 2. CREACIÓN DE ARRAYS 2D
print("\n2. ARRAYS BIDIMENSIONALES (2D):")
# Crear array 2D (matriz 3x4)
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])
print("Array 2D (3x4):")
print(array_2d)

# Mostrar atributos del array 2D
print("   .shape  :", array_2d.shape)    # (filas, columnas)
print("   .ndim   :", array_2d.ndim)     # 2 dimensiones
print("   .dtype  :", array_2d.dtype)    # Tipo de datos
print("   .size   :", array_2d.size)     # 12 elementos (3x4)

print("\n" + "="*60)


2. ARRAYS BIDIMENSIONALES (2D):
Array 2D (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
   .shape  : (3, 4)
   .ndim   : 2
   .dtype  : int64
   .size   : 12



In [ ]:
# 3. SLICING EN ARRAYS 1D
print("\n3. SLICING EN ARRAYS 1D:")
print("Array original:", array_1d)
print("   array[2:6]    :", array_1d[1:5])     # Elementos del índice 2 al 5
print("   array[:5]     :", array_1d[:5])      # Primeros 5 elementos
print("   array[7:]     :", array_1d[7:])      # Desde índice 7 hasta el final
print("   array[::2]    :", array_1d[::2])     # Cada 2 elementos (pares)
print("   array[1::2]   :", array_1d[1::2])    # Cada 2 elementos (impares)
print("   array[-3:]    :", array_1d[-3:])     # Últimos 3 elementos
print("   array[::-1]   :", array_1d[::-1])    # Array invertido

print("\n" + "="*60)


3. SLICING EN ARRAYS 1D:
Array original: [ 1  2  3  4  5  6  7  8  9 10]
   array[2:6]    : [3 4 5 6]
   array[:5]     : [1 2 3 4 5]
   array[7:]     : [ 8  9 10]
   array[::2]    : [1 3 5 7 9]
   array[1::2]   : [ 2  4  6  8 10]
   array[-3:]    : [ 8  9 10]
   array[::-1]   : [10  9  8  7  6  5  4  3  2  1]



In [ ]:

# 4. SLICING EN ARRAYS 2D
print("\n4. SLICING EN ARRAYS 2D:")
print("Array 2D original:")
print(array_2d)

print("\nSlicing por filas y columnas:")
print("   array[0, :]     - Primera fila completa:", array_2d[0, :])
print("   array[:, 1]     - Segunda columna completa:", array_2d[:, 1])
print("   array[1, 2]     - Elemento fila 1, columna 2:", array_2d[1, 2])

print("\nSubmatrices:")
print("   array[:2, :3]   - Primeras 2 filas, primeras 3 columnas:")
print(array_2d[:2, :3])

print("   array[1:, 2:]   - Desde fila 1, desde columna 2:")
print(array_2d[1:, 2:])

print("   array[::2, ::2] - Filas y columnas pares:")
print(array_2d[::2, ::2])

print("\n" + "="*60)




4. SLICING EN ARRAYS 2D:
Array 2D original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Slicing por filas y columnas:
   array[0, :]     - Primera fila completa: [1 2 3 4]
   array[:, 1]     - Segunda columna completa: [ 2  6 10]
   array[1, 2]     - Elemento fila 1, columna 2: 7

Submatrices:
   array[:2, :3]   - Primeras 2 filas, primeras 3 columnas:
[[1 2 3]
 [5 6 7]]
   array[1:, 2:]   - Desde fila 1, desde columna 2:
[[ 7  8]
 [11 12]]
   array[::2, ::2] - Filas y columnas pares:
[[ 1  3]
 [ 9 11]]



In [ ]:
# 5. ARRAYS CON DIFERENTES TIPOS DE DATOS
import numpy as np

print("\n5. TIPOS DE DATOS EN NUMPY:")
# Arrays con diferentes tipos de datos
array_int = np.array([1, 2, 3], dtype=np.int32)
array_float = np.array([1.1, 2.2, 3.3], dtype=np.float64)
array_bool = np.array([True, False, True], dtype=np.bool_)

print("   Enteros 32-bit:", array_int, "- dtype:", array_int.dtype)
print("   Flotantes 64-bit:", array_float, "- dtype:", array_float.dtype)
print("   Booleanos:", array_bool, "- dtype:", array_bool.dtype)

print("\n" + "="*60)


5. TIPOS DE DATOS EN NUMPY:
   Enteros 32-bit: [1 2 3] - dtype: int32
   Flotantes 64-bit: [1.1 2.2 3.3] - dtype: float64
   Booleanos: [ True False  True] - dtype: bool



In [ ]:
# 6. EJEMPLO PRÁCTICO: PROCESAMIENTO DE DATOS
import numpy as np

print("\n6. EJEMPLO PRÁCTICO: ANÁLISIS DE TEMPERATURAS")
# Datos de temperatura por hora (24 horas)
temperaturas = np.array([22.5, 22.1, 21.8, 21.5, 21.0, 20.8, 21.2,
                         22.0, 23.5, 25.0, 26.8, 28.0, 29.2, 29.8,
                         30.0, 29.5, 28.8, 27.5, 26.0, 24.5, 23.5,
                         23.0, 22.8, 22.5])

print("Temperaturas por hora (24h):")
print(temperaturas)
print("Forma del array:", temperaturas.shape)

# Análisis usando slicing
print("\nAnálisis:")
print("   Temperatura máxima:", temperaturas.max())
print("   Temperatura mínima:", temperaturas.min())
print("   Promedio:", temperaturas.mean())
print("   Temperaturas diurnas (6am-6pm):", temperaturas[6:18])
print("   Promedio nocturno (8pm-6am):",
      np.concatenate([temperaturas[20:], temperaturas[:6]]).mean())

print("\n¡Programa terminado! ♥")


6. EJEMPLO PRÁCTICO: ANÁLISIS DE TEMPERATURAS
Temperaturas por hora (24h):
[22.5 22.1 21.8 21.5 21.  20.8 21.2 22.  23.5 25.  26.8 28.  29.2 29.8
 30.  29.5 28.8 27.5 26.  24.5 23.5 23.  22.8 22.5]
Forma del array: (24,)

Análisis:
   Temperatura máxima: 30.0
   Temperatura mínima: 20.8
   Promedio: 24.72083333333333
   Temperaturas diurnas (6am-6pm): [21.2 22.  23.5 25.  26.8 28.  29.2 29.8 30.  29.5 28.8 27.5]
   Promedio nocturno (8pm-6am): 22.15

¡Programa terminado! ♥
